"""musicbrainz tables

Revision ID: dff1e8dbc207
Revises: 0b61c8daf4e8
Create Date: 2024-04-28 13:37:09.276248

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'dff1e8dbc207'
down_revision = '0b61c8daf4e8'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SCHEMA musicbrainz")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_credit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('enum_area_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_artist_alias_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_artist_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_event_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_gender_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_instrument_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_label_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_language_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_medium_format_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_place_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_recording_alias_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_release_group_secondary_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_release_group_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_release_status_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_series_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('enum_work_type_values',
    sa.Column('id_value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_value'),
    schema='musicbrainz'
    )
    op.create_table('link_attribute_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('root', sa.Integer(), nullable=False),
    sa.Column('child_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['musicbrainz.link_attribute_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root'], ['musicbrainz.link_attribute_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_link_attribute_type_mbid'), 'link_attribute_type', ['mbid'], unique=True, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_link_attribute_type_parent'), 'link_attribute_type', ['parent'], unique=False, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_link_attribute_type_root'), 'link_attribute_type', ['root'], unique=False, schema='musicbrainz')
    op.create_table('link_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('entity_type0', sa.Text(), nullable=False),
    sa.Column('entity_type1', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link_phrase', sa.Text(), nullable=True),
    sa.Column('reverse_link_phrase', sa.Text(), nullable=True),
    sa.Column('long_link_phrase', sa.Text(), nullable=True),
    sa.Column('entity0_cardinality', sa.Integer(), nullable=True),
    sa.Column('entity1_cardinality', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_link_type_mbid'), 'link_type', ['mbid'], unique=True, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_link_type_name'), 'link_type', ['name'], unique=False, schema='musicbrainz')
    op.create_table('area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('area_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_type'], ['musicbrainz.enum_area_type_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_area_mbid'), 'area', ['mbid'], unique=True, schema='musicbrainz')
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Integer(), nullable=True),
    sa.Column('begin_date_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_date_month', sa.SmallInteger(), nullable=True),
    sa.Column('begin_date_day', sa.SmallInteger(), nullable=True),
    sa.Column('end_date_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_date_month', sa.SmallInteger(), nullable=True),
    sa.Column('end_date_day', sa.SmallInteger(), nullable=True),
    sa.Column('setlist', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_type'], ['musicbrainz.enum_event_type_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_event_mbid'), 'event', ['mbid'], unique=True, schema='musicbrainz')
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['musicbrainz.enum_instrument_type_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_instrument_mbid'), 'instrument', ['mbid'], unique=True, schema='musicbrainz')
    op.create_table('link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_type_id', sa.Integer(), nullable=False),
    sa.Column('begin_date_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_date_month', sa.SmallInteger(), nullable=True),
    sa.Column('begin_date_day', sa.SmallInteger(), nullable=True),
    sa.Column('end_date_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_date_month', sa.SmallInteger(), nullable=True),
    sa.Column('end_date_day', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['link_type_id'], ['musicbrainz.link_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_link_link_type_id'), 'link', ['link_type_id'], unique=False, schema='musicbrainz')
    op.create_table('recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('disambiguation', sa.Text(), nullable=True),
    sa.Column('artist_credit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_credit_id'], ['musicbrainz.artist_credit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_recording_artist_credit_id'), 'recording', ['artist_credit_id'], unique=False, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_recording_mbid'), 'recording', ['mbid'], unique=True, schema='musicbrainz')
    op.create_table('release_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('disambiguation', sa.Text(), nullable=True),
    sa.Column('release_group_type', sa.Integer(), nullable=True),
    sa.Column('artist_credit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_credit_id'], ['musicbrainz.artist_credit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_group_type'], ['musicbrainz.enum_release_group_type_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_release_group_artist_credit_id'), 'release_group', ['artist_credit_id'], unique=False, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_release_group_mbid'), 'release_group', ['mbid'], unique=True, schema='musicbrainz')
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('disambiguation', sa.Text(), nullable=True),
    sa.Column('series_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_type'], ['musicbrainz.enum_series_type_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_series_mbid'), 'series', ['mbid'], unique=True, schema='musicbrainz')
    op.create_table('work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('disambiguation', sa.Text(), nullable=True),
    sa.Column('work_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['work_type'], ['musicbrainz.enum_work_type_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_work_mbid'), 'work', ['mbid'], unique=True, schema='musicbrainz')
    op.create_table('artist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('disambiguation', sa.Text(), nullable=True),
    sa.Column('sort_name', sa.Text(), nullable=True),
    sa.Column('artist_type', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_type'], ['musicbrainz.enum_artist_type_values.id_value'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gender'], ['musicbrainz.enum_gender_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_artist_mbid'), 'artist', ['mbid'], unique=True, schema='musicbrainz')
    op.create_table('l_area_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_area_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_area_instrument',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_area_recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_area_release_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_area_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_area_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_event_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_event_instrument',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_event_recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_event_release_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_event_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_event_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_instrument_instrument',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_instrument_recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_instrument_release_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_instrument_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_instrument_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_recording_recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_recording_release_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_recording_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_recording_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_release_group_release_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_release_group_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_release_group_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_series_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_series_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_work_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('disambiguation', sa.Text(), nullable=True),
    sa.Column('label_type', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('begin_date_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_date_month', sa.SmallInteger(), nullable=True),
    sa.Column('begin_date_day', sa.SmallInteger(), nullable=True),
    sa.Column('end_date_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_date_month', sa.SmallInteger(), nullable=True),
    sa.Column('end_date_day', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_type'], ['musicbrainz.enum_label_type_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_label_mbid'), 'label', ['mbid'], unique=True, schema='musicbrainz')
    op.create_table('link_attribute',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('link_attribute_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_attribute_type_id'], ['musicbrainz.link_attribute_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id', 'link_attribute_type_id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_link_attribute_link_attribute_type_id'), 'link_attribute', ['link_attribute_type_id'], unique=False, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_link_attribute_link_id'), 'link_attribute', ['link_id'], unique=False, schema='musicbrainz')
    op.create_table('link_attribute_credit',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('link_attribute_type_id', sa.Integer(), nullable=False),
    sa.Column('credited_as', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['link_attribute_type_id'], ['musicbrainz.link_attribute_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id', 'link_attribute_type_id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_link_attribute_credit_link_attribute_type_id'), 'link_attribute_credit', ['link_attribute_type_id'], unique=False, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_link_attribute_credit_link_id'), 'link_attribute_credit', ['link_id'], unique=False, schema='musicbrainz')
    op.create_table('place',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('disambiguation', sa.Text(), nullable=True),
    sa.Column('place_type', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_type'], ['musicbrainz.enum_place_type_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_place_mbid'), 'place', ['mbid'], unique=True, schema='musicbrainz')
    op.create_table('recording_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sort_name', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=True),
    sa.Column('recording_alias_type', sa.Integer(), nullable=True),
    sa.Column('primary_for_locale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['recording_alias_type'], ['musicbrainz.enum_recording_alias_type_values.id_value'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_recording_alias_recording_id'), 'recording_alias', ['recording_id'], unique=False, schema='musicbrainz')
    op.create_table('release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('disambiguation', sa.Text(), nullable=True),
    sa.Column('artist_credit_id', sa.Integer(), nullable=True),
    sa.Column('release_group_id', sa.Integer(), nullable=True),
    sa.Column('release_status', sa.Integer(), nullable=True),
    sa.Column('language', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artist_credit_id'], ['musicbrainz.artist_credit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language'], ['musicbrainz.enum_language_values.id_value'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_group_id'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_status'], ['musicbrainz.enum_release_status_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_release_artist_credit_id'), 'release', ['artist_credit_id'], unique=False, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_release_mbid'), 'release', ['mbid'], unique=True, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_release_release_group_id'), 'release', ['release_group_id'], unique=False, schema='musicbrainz')
    op.create_table('release_group_secondary_type_join',
    sa.Column('release_group_id', sa.Integer(), nullable=False),
    sa.Column('secondary_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_group_id'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secondary_type'], ['musicbrainz.enum_release_group_secondary_type_values.id_value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('release_group_id'),
    schema='musicbrainz'
    )
    op.create_table('artist_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sort_name', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=True),
    sa.Column('artist_alias_type', sa.Integer(), nullable=True),
    sa.Column('primary_for_locale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['artist_alias_type'], ['musicbrainz.enum_artist_alias_type_values.id_value'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_id'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_artist_alias_artist_id'), 'artist_alias', ['artist_id'], unique=False, schema='musicbrainz')
    op.create_table('artist_credit_name',
    sa.Column('artist_credit_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('join_phrase', sa.Text(), server_default='', nullable=True),
    sa.ForeignKeyConstraint(['artist_credit_id'], ['musicbrainz.artist_credit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_id'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_artist_credit_name_artist_credit_id'), 'artist_credit_name', ['artist_credit_id'], unique=False, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_artist_credit_name_artist_id'), 'artist_credit_name', ['artist_id'], unique=False, schema='musicbrainz')
    op.create_table('l_area_artist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_area_label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_area_place',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_area_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_artist_artist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_artist_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_artist_instrument',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_artist_label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_artist_place',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_artist_recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_artist_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_artist_release_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_artist_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_artist_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_event_label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_event_place',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_event_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_instrument_label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_instrument_place',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_instrument_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_label_label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_label_place',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_label_recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_label_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_label_release_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_label_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_label_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_place_place',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_place_recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_place_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_place_release_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_place_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_place_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_recording_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_release_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_release_release_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.release_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_release_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('l_release_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('entity0', sa.Integer(), nullable=False),
    sa.Column('entity1', sa.Integer(), nullable=False),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('entity0_credit', sa.Text(), nullable=True),
    sa.Column('entity1_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity0'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity1'], ['musicbrainz.work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['musicbrainz.link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_table('medium',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['format'], ['musicbrainz.enum_medium_format_values.id_value'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_medium_release_id'), 'medium', ['release_id'], unique=False, schema='musicbrainz')
    op.create_table('release_country',
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('date_year', sa.SmallInteger(), nullable=True),
    sa.Column('date_month', sa.SmallInteger(), nullable=True),
    sa.Column('date_day', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['musicbrainz.area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('release_id', 'country_id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_release_country_release_id'), 'release_country', ['release_id'], unique=False, schema='musicbrainz')
    op.create_table('release_label',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('catalog_number', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['musicbrainz.label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_release_label_release_id'), 'release_label', ['release_id'], unique=False, schema='musicbrainz')
    op.create_table('release_unknown_country',
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('date_year', sa.SmallInteger(), nullable=True),
    sa.Column('date_month', sa.SmallInteger(), nullable=True),
    sa.Column('date_day', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('release_id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_release_unknown_country_release_id'), 'release_unknown_country', ['release_id'], unique=False, schema='musicbrainz')
    op.create_table('track',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mbid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('number_text', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('artist_credit_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('is_data_track', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['artist_credit_id'], ['musicbrainz.artist_credit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medium_id'], ['musicbrainz.medium.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['musicbrainz.recording.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='musicbrainz'
    )
    op.create_index(op.f('ix_musicbrainz_track_mbid'), 'track', ['mbid'], unique=True, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_track_medium_id'), 'track', ['medium_id'], unique=False, schema='musicbrainz')
    op.create_index(op.f('ix_musicbrainz_track_recording_id'), 'track', ['recording_id'], unique=False, schema='musicbrainz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_musicbrainz_track_recording_id'), table_name='track', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_track_medium_id'), table_name='track', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_track_mbid'), table_name='track', schema='musicbrainz')
    op.drop_table('track', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_release_unknown_country_release_id'), table_name='release_unknown_country', schema='musicbrainz')
    op.drop_table('release_unknown_country', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_release_label_release_id'), table_name='release_label', schema='musicbrainz')
    op.drop_table('release_label', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_release_country_release_id'), table_name='release_country', schema='musicbrainz')
    op.drop_table('release_country', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_medium_release_id'), table_name='medium', schema='musicbrainz')
    op.drop_table('medium', schema='musicbrainz')
    op.drop_table('l_release_work', schema='musicbrainz')
    op.drop_table('l_release_series', schema='musicbrainz')
    op.drop_table('l_release_release_group', schema='musicbrainz')
    op.drop_table('l_release_release', schema='musicbrainz')
    op.drop_table('l_recording_release', schema='musicbrainz')
    op.drop_table('l_place_work', schema='musicbrainz')
    op.drop_table('l_place_series', schema='musicbrainz')
    op.drop_table('l_place_release_group', schema='musicbrainz')
    op.drop_table('l_place_release', schema='musicbrainz')
    op.drop_table('l_place_recording', schema='musicbrainz')
    op.drop_table('l_place_place', schema='musicbrainz')
    op.drop_table('l_label_work', schema='musicbrainz')
    op.drop_table('l_label_series', schema='musicbrainz')
    op.drop_table('l_label_release_group', schema='musicbrainz')
    op.drop_table('l_label_release', schema='musicbrainz')
    op.drop_table('l_label_recording', schema='musicbrainz')
    op.drop_table('l_label_place', schema='musicbrainz')
    op.drop_table('l_label_label', schema='musicbrainz')
    op.drop_table('l_instrument_release', schema='musicbrainz')
    op.drop_table('l_instrument_place', schema='musicbrainz')
    op.drop_table('l_instrument_label', schema='musicbrainz')
    op.drop_table('l_event_release', schema='musicbrainz')
    op.drop_table('l_event_place', schema='musicbrainz')
    op.drop_table('l_event_label', schema='musicbrainz')
    op.drop_table('l_artist_work', schema='musicbrainz')
    op.drop_table('l_artist_series', schema='musicbrainz')
    op.drop_table('l_artist_release_group', schema='musicbrainz')
    op.drop_table('l_artist_release', schema='musicbrainz')
    op.drop_table('l_artist_recording', schema='musicbrainz')
    op.drop_table('l_artist_place', schema='musicbrainz')
    op.drop_table('l_artist_label', schema='musicbrainz')
    op.drop_table('l_artist_instrument', schema='musicbrainz')
    op.drop_table('l_artist_event', schema='musicbrainz')
    op.drop_table('l_artist_artist', schema='musicbrainz')
    op.drop_table('l_area_release', schema='musicbrainz')
    op.drop_table('l_area_place', schema='musicbrainz')
    op.drop_table('l_area_label', schema='musicbrainz')
    op.drop_table('l_area_artist', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_artist_credit_name_artist_id'), table_name='artist_credit_name', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_artist_credit_name_artist_credit_id'), table_name='artist_credit_name', schema='musicbrainz')
    op.drop_table('artist_credit_name', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_artist_alias_artist_id'), table_name='artist_alias', schema='musicbrainz')
    op.drop_table('artist_alias', schema='musicbrainz')
    op.drop_table('release_group_secondary_type_join', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_release_release_group_id'), table_name='release', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_release_mbid'), table_name='release', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_release_artist_credit_id'), table_name='release', schema='musicbrainz')
    op.drop_table('release', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_recording_alias_recording_id'), table_name='recording_alias', schema='musicbrainz')
    op.drop_table('recording_alias', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_place_mbid'), table_name='place', schema='musicbrainz')
    op.drop_table('place', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_link_attribute_credit_link_id'), table_name='link_attribute_credit', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_link_attribute_credit_link_attribute_type_id'), table_name='link_attribute_credit', schema='musicbrainz')
    op.drop_table('link_attribute_credit', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_link_attribute_link_id'), table_name='link_attribute', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_link_attribute_link_attribute_type_id'), table_name='link_attribute', schema='musicbrainz')
    op.drop_table('link_attribute', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_label_mbid'), table_name='label', schema='musicbrainz')
    op.drop_table('label', schema='musicbrainz')
    op.drop_table('l_work_work', schema='musicbrainz')
    op.drop_table('l_series_work', schema='musicbrainz')
    op.drop_table('l_series_series', schema='musicbrainz')
    op.drop_table('l_release_group_work', schema='musicbrainz')
    op.drop_table('l_release_group_series', schema='musicbrainz')
    op.drop_table('l_release_group_release_group', schema='musicbrainz')
    op.drop_table('l_recording_work', schema='musicbrainz')
    op.drop_table('l_recording_series', schema='musicbrainz')
    op.drop_table('l_recording_release_group', schema='musicbrainz')
    op.drop_table('l_recording_recording', schema='musicbrainz')
    op.drop_table('l_instrument_work', schema='musicbrainz')
    op.drop_table('l_instrument_series', schema='musicbrainz')
    op.drop_table('l_instrument_release_group', schema='musicbrainz')
    op.drop_table('l_instrument_recording', schema='musicbrainz')
    op.drop_table('l_instrument_instrument', schema='musicbrainz')
    op.drop_table('l_event_work', schema='musicbrainz')
    op.drop_table('l_event_series', schema='musicbrainz')
    op.drop_table('l_event_release_group', schema='musicbrainz')
    op.drop_table('l_event_recording', schema='musicbrainz')
    op.drop_table('l_event_instrument', schema='musicbrainz')
    op.drop_table('l_event_event', schema='musicbrainz')
    op.drop_table('l_area_work', schema='musicbrainz')
    op.drop_table('l_area_series', schema='musicbrainz')
    op.drop_table('l_area_release_group', schema='musicbrainz')
    op.drop_table('l_area_recording', schema='musicbrainz')
    op.drop_table('l_area_instrument', schema='musicbrainz')
    op.drop_table('l_area_event', schema='musicbrainz')
    op.drop_table('l_area_area', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_artist_mbid'), table_name='artist', schema='musicbrainz')
    op.drop_table('artist', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_work_mbid'), table_name='work', schema='musicbrainz')
    op.drop_table('work', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_series_mbid'), table_name='series', schema='musicbrainz')
    op.drop_table('series', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_release_group_mbid'), table_name='release_group', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_release_group_artist_credit_id'), table_name='release_group', schema='musicbrainz')
    op.drop_table('release_group', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_recording_mbid'), table_name='recording', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_recording_artist_credit_id'), table_name='recording', schema='musicbrainz')
    op.drop_table('recording', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_link_link_type_id'), table_name='link', schema='musicbrainz')
    op.drop_table('link', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_instrument_mbid'), table_name='instrument', schema='musicbrainz')
    op.drop_table('instrument', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_event_mbid'), table_name='event', schema='musicbrainz')
    op.drop_table('event', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_area_mbid'), table_name='area', schema='musicbrainz')
    op.drop_table('area', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_link_type_name'), table_name='link_type', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_link_type_mbid'), table_name='link_type', schema='musicbrainz')
    op.drop_table('link_type', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_link_attribute_type_root'), table_name='link_attribute_type', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_link_attribute_type_parent'), table_name='link_attribute_type', schema='musicbrainz')
    op.drop_index(op.f('ix_musicbrainz_link_attribute_type_mbid'), table_name='link_attribute_type', schema='musicbrainz')
    op.drop_table('link_attribute_type', schema='musicbrainz')
    op.drop_table('enum_work_type_values', schema='musicbrainz')
    op.drop_table('enum_series_type_values', schema='musicbrainz')
    op.drop_table('enum_release_status_values', schema='musicbrainz')
    op.drop_table('enum_release_group_type_values', schema='musicbrainz')
    op.drop_table('enum_release_group_secondary_type_values', schema='musicbrainz')
    op.drop_table('enum_recording_alias_type_values', schema='musicbrainz')
    op.drop_table('enum_place_type_values', schema='musicbrainz')
    op.drop_table('enum_medium_format_values', schema='musicbrainz')
    op.drop_table('enum_language_values', schema='musicbrainz')
    op.drop_table('enum_label_type_values', schema='musicbrainz')
    op.drop_table('enum_instrument_type_values', schema='musicbrainz')
    op.drop_table('enum_gender_values', schema='musicbrainz')
    op.drop_table('enum_event_type_values', schema='musicbrainz')
    op.drop_table('enum_artist_type_values', schema='musicbrainz')
    op.drop_table('enum_artist_alias_type_values', schema='musicbrainz')
    op.drop_table('enum_area_type_values', schema='musicbrainz')
    op.drop_table('artist_credit', schema='musicbrainz')
    # ### end Alembic commands ###
