"""core tables related to musicbrainz

Revision ID: 3891d7a39db9
Revises: dff1e8dbc207
Create Date: 2024-04-28 13:40:13.604312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3891d7a39db9'
down_revision = 'dff1e8dbc207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_credits_mb',
    sa.Column('artist_credit_id', sa.Integer(), nullable=False),
    sa.Column('artist_path_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_credit_id'], ['musicbrainz.artist_credit.id'], name='artist_credits_mb_artist_credit_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_path_id'], ['artist_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artist_credit_id')
    )
    op.create_table('album_release',
    sa.Column('album_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('release_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['musicbrainz.release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_index(op.f('ix_album_release_release_id'), 'album_release', ['release_id'], unique=False)
    op.create_table('artists_mb',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('locale_name', sa.Text(), nullable=True),
    sa.Column('locale_sort_name', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=True),
    sa.Column('artist_alias_type', sa.Integer(), nullable=True),
    sa.Column('artist_path_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_path_id'], ['artist_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['musicbrainz.artist.id'], name='artists_mb_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists_ratings',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists_mb.id'], name='artists_ratings_artist_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('user_id', 'artist_id', name='artists_ratings_user_id_artist_id_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists_ratings')
    op.drop_table('artists_mb')
    op.drop_index(op.f('ix_album_release_release_id'), table_name='album_release')
    op.drop_table('album_release')
    op.drop_table('artist_credits_mb')
    # ### end Alembic commands ###
