"""rating views

Revision ID: 9c004703b14a
Revises: fedc1349bd1a
Create Date: 2024-04-28 13:53:01.852721

"""
from alembic import op
import sqlalchemy as sa
from bard.alembic.cookbook import ReplaceableObject


# revision identifiers, used by Alembic.
revision = '9c004703b14a'
down_revision = 'fedc1349bd1a'
branch_labels = None
depends_on = None

avg_songs_ratings_view = ReplaceableObject('avg_songs_ratings',
    """
  SELECT songs_ratings.song_id,
    users.id AS user_id,
    round(avg(songs_ratings.rating)) AS avg_rating
   FROM songs_ratings,
    users
  WHERE songs_ratings.user_id <> users.id
  GROUP BY songs_ratings.song_id, users.id"""
)

avg_albums_ratings_view = ReplaceableObject('avg_albums_ratings',
    """
  SELECT albums_ratings.album_id,
    users.id AS user_id,
    round(avg(albums_ratings.rating)) AS avg_rating
   FROM albums_ratings,
    users
  WHERE albums_ratings.user_id <> users.id
  GROUP BY albums_ratings.album_id, users.id"""
)

avg_artists_ratings_view = ReplaceableObject('avg_artists_ratings',
    """
  SELECT artists_ratings.artist_id,
    users.id AS user_id,
    round(avg(artists_ratings.rating)) AS avg_rating
   FROM artists_ratings,
    users
  WHERE artists_ratings.user_id <> users.id
  GROUP BY artists_ratings.artist_id, users.id"""
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_view(avg_songs_ratings_view)
    op.create_view(avg_albums_ratings_view)
    op.create_view(avg_artists_ratings_view)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_view(avg_artists_ratings_view)
    op.drop_view(avg_albums_ratings_view)
    op.drop_view(avg_songs_ratings_view)
    # ### end Alembic commands ###
